name: 'RSS Feed Fetch Action'
description: 'Fetches an RSS feed and optionally saves it to a file'
author: 'Christopher C. Smith <christopher.smith@promptlytechnologies.com>'

inputs:
  feed_url:
    description: 'The URL of the RSS feed to fetch'
    required: true
  file_path:
    description: 'The relative file path to save the fetched RSS feed'
    required: false

outputs:
  feed:
    description: 'The fetched RSS feed in JSON format'

runs:
  using: node20
  main: dist/index.js
