name: 'RSS Feed Fetch Action'
description: 'Fetches an RSS feed and saves it to a file'
author: 'Christopher C. Smith <christopher.smith@promptlytechnologies.com>'
branding:
  icon: 'rss'

inputs:
  feed_url:
    description: 'The URL of the RSS feed to fetch'
    required: true
  file_path:
    description: 'The relative file path at which to save the fetched RSS feed'
    required: true
  parser_options:
    description: 'JSON string for parser options'
    required: false
  fetch_options:
    description: 'JSON string for fetch options'
    required: false

runs:
  using: node20
  main: dist/index.js