name: 'RSS Feed Fetch Action'
description: 'Fetches an RSS feed and saves it to a file'
author: 'Christopher C. Smith <christopher.smith@promptlytechnologies.com>'

inputs:
  feed_url:
    description: 'The URL of the RSS feed to fetch'
    required: true
  file_path:
    description: 'The relative file path at which to save the fetched RSS feed'
    required: true
  remove_last_build_date:
    description: 'Remove the lastBuildDate tag from the fetched RSS feed for easier diffing'
    required: false
    default: false

runs:
  using: node20
  main: dist/index.js
