name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "releases/*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  statuses: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Print ncc version
        run: npx ncc --version

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test

      - name: Build dist/ Directory
        if: github.ref == 'refs/heads/main'
        run: npm run bundle

      - name: GitHub Actions Test with JSON
        uses: ./
        with:
          feed_url: "https://modelingmarkets.substack.com/feed"
          file_path: "temp.json"

      - name: Validate JSON
        run: node -e "const fs = require('fs'); const data = fs.readFileSync('temp.json', 'utf8'); const obj = JSON.parse(data); if (!obj || !obj.rss || !obj.rss.$) { console.error('Invalid object'); process.exit(1); }"

      - name: GitHub Actions Test with XML
        uses: ./
        with:
          feed_url: "https://modelingmarkets.substack.com/feed"
          file_path: "temp.xml"

      - name: Validate XML
        run: node -e "const fs = require('fs'); const data = fs.readFileSync('temp.xml', 'utf8'); if (!data.includes('<rss') || !data.includes('</rss>')) { console.error('Invalid XML'); process.exit(1); }"

      - name: Push dist/ Directory
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated build & deploy [skip ci]'
