name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
      - feed-extractor-version

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Github Action with JSON
        uses: ./
        with:
          feed_url: "https://feed.zazzle.com/store/promptlytechnologies/rss"
          file_path: "./feed.json"
          parser_options: "{\"useISODateFormat\": false, \"normalization\": false}"

      - name: Validate JSON
        run: |
          node -e "
          const fs = require('fs');
          const data = fs.readFileSync('./feed.json', 'utf8');
          const obj = JSON.parse(data);
          if (!obj || 
              !obj.title || 
              !obj.link || 
              !obj.description || 
              !obj.generator || 
              !obj.language || 
              !obj.published || 
              !Array.isArray(obj.entries) || 
              obj.entries.length === 0 || 
              !obj.entries[0]['content:encoded']) {
            console.error('Invalid object');
            process.exit(1);
          }
          "
      
