name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          feed_url: "https://modelingmarkets.substack.com/feed"

      - name: Escape and Validate JSON structure
        run: |
          escaped_json=$(echo "${{ steps.test-action.outputs.feed }}" | jq -c -r @uri)
          echo "Escaped JSON: $escaped_json"
          js_command="const obj = JSON.parse(decodeURI('$escaped_json')); if (!obj || !obj.rss || !obj.rss.$) { console.error('Invalid object'); process.exit(1); }"
          echo "JS Command: $js_command"
          echo $js_command | node -e
        
  